/**
 * 中国传统色彩数据
 * 数据来源：中国色网站
 */

export const chineseColors = [
  { name: '胭脂', pinyin: 'Yan Zhi', hex: '#9D2933' },
  { name: '朱砂', pinyin: 'Zhu Sha', hex: '#FF4C00' },
  { name: '石榴红', pinyin: 'Shi Liu Hong', hex: '#F20C00' },
  { name: '樱桃色', pinyin: 'Ying Tao Se', hex: '#C93756' },
  { name: '银红', pinyin: 'Yin Hong', hex: '#F05654' },
  { name: '大红', pinyin: 'Da Hong', hex: '#FF2121' },
  { name: '绛紫', pinyin: 'Jiang Zi', hex: '#8C4356' },
  { name: '绯红', pinyin: 'Fei Hong', hex: '#C83C23' },
  { name: '妃色', pinyin: 'Fei Se', hex: '#ED5736' },
  { name: '洋红', pinyin: 'Yang Hong', hex: '#FF0097' },
  { name: '品红', pinyin: 'Pin Hong', hex: '#F00056' },
  { name: '桃红', pinyin: 'Tao Hong', hex: '#F47983' },
  { name: '海棠红', pinyin: 'Hai Tang Hong', hex: '#DB5A6B' },
  { name: '樱桃红', pinyin: 'Ying Tao Hong', hex: '#C93756' },
  { name: '酡红', pinyin: 'Tuo Hong', hex: '#DC3023' },
  { name: '杏红', pinyin: 'Xing Hong', hex: '#FF8C31' },
  { name: '橘红', pinyin: 'Ju Hong', hex: '#FF7500' },
  { name: '橙色', pinyin: 'Cheng Se', hex: '#FA8C35' },
  { name: '杏黄', pinyin: 'Xing Huang', hex: '#FFA631' },
  { name: '橘黄', pinyin: 'Ju Huang', hex: '#FF8936' },
  { name: '姜黄', pinyin: 'Jiang Huang', hex: '#FFC773' },
  { name: '缃色', pinyin: 'Xiang Se', hex: '#F0C239' },
  { name: '橙黄', pinyin: 'Cheng Huang', hex: '#FFA400' },
  { name: '琥珀', pinyin: 'Hu Po', hex: '#CA6924' },
  { name: '棕色', pinyin: 'Zong Se', hex: '#B25D25' },
  { name: '茶色', pinyin: 'Cha Se', hex: '#B35C44' },
  { name: '驼色', pinyin: 'Tuo Se', hex: '#A88462' },
  { name: '昏黄', pinyin: 'Hun Huang', hex: '#C89B40' },
  { name: '栗色', pinyin: 'Li Se', hex: '#60281E' },
  { name: '棕黑', pinyin: 'Zong Hei', hex: '#7C4B00' },
  { name: '赭色', pinyin: 'Zhe Se', hex: '#955539' },
  { name: '柳黄', pinyin: 'Liu Huang', hex: '#C9DD22' },
  { name: '嫩绿', pinyin: 'Nen Lv', hex: '#BDDD22' },
  { name: '柳绿', pinyin: 'Liu Lv', hex: '#AFDD22' },
  { name: '葱绿', pinyin: 'Cong Lv', hex: '#9ED900' },
  { name: '豆绿', pinyin: 'Dou Lv', hex: '#9ED048' },
  { name: '青葱', pinyin: 'Qing Cong', hex: '#0AA344' },
  { name: '青翠', pinyin: 'Qing Cui', hex: '#00BC12' },
  { name: '翠绿', pinyin: 'Cui Lv', hex: '#00E079' },
  { name: '碧绿', pinyin: 'Bi Lv', hex: '#2ADD9C' },
  { name: '石绿', pinyin: 'Shi Lv', hex: '#16A951' },
  { name: '松柏绿', pinyin: 'Song Bai Lv', hex: '#21A675' },
  { name: '松花绿', pinyin: 'Song Hua Lv', hex: '#057748' },
  { name: '绿沈', pinyin: 'Lv Shen', hex: '#0C8918' },
  { name: '青色', pinyin: 'Qing Se', hex: '#00E09E' },
  { name: '碧色', pinyin: 'Bi Se', hex: '#1BD1A5' },
  { name: '青碧', pinyin: 'Qing Bi', hex: '#48C0A3' },
  { name: '石青', pinyin: 'Shi Qing', hex: '#7BCFA6' },
  { name: '竹青', pinyin: 'Zhu Qing', hex: '#789262' },
  { name: '蓝', pinyin: 'Lan', hex: '#44CEF6' },
  { name: '靛青', pinyin: 'Dian Qing', hex: '#177CB0' },
  { name: '靛蓝', pinyin: 'Dian Lan', hex: '#065279' },
  { name: '碧蓝', pinyin: 'Bi Lan', hex: '#3EEDE7' },
  { name: '蔚蓝', pinyin: 'Wei Lan', hex: '#70F3FF' },
  { name: '宝蓝', pinyin: 'Bao Lan', hex: '#4B5CC4' },
  { name: '藏蓝', pinyin: 'Cang Lan', hex: '#3B2E7E' },
  { name: '黛', pinyin: 'Dai', hex: '#4A4266' },
  { name: '黛绿', pinyin: 'Dai Lv', hex: '#426666' },
  { name: '黛蓝', pinyin: 'Dai Lan', hex: '#425066' },
  { name: '紫色', pinyin: 'Zi Se', hex: '#8D4BBB' },
  { name: '紫酱', pinyin: 'Zi Jiang', hex: '#815463' },
  { name: '酱紫', pinyin: 'Jiang Zi', hex: '#815476' },
  { name: '紫檀', pinyin: 'Zi Tan', hex: '#4C221B' },
  { name: '绀青', pinyin: 'Gan Qing', hex: '#003371' },
  { name: '紫棠', pinyin: 'Zi Tang', hex: '#56004F' },
  { name: '青莲', pinyin: 'Qing Lian', hex: '#801DAE' },
  { name: '群青', pinyin: 'Qun Qing', hex: '#4C8DAE' },
  { name: '雪青', pinyin: 'Xue Qing', hex: '#B0A4E3' },
  { name: '丁香色', pinyin: 'Ding Xiang Se', hex: '#CCA4E3' },
  { name: '藕色', pinyin: 'Ou Se', hex: '#EDD1D8' },
  { name: '藕荷色', pinyin: 'Ou He Se', hex: '#E4C6D0' },
  { name: '水红', pinyin: 'Shui Hong', hex: '#F3D3E7' },
  { name: '月白', pinyin: 'Yue Bai', hex: '#D6ECF0' },
  { name: '缟', pinyin: 'Gao', hex: '#F2ECDE' },
  { name: '素', pinyin: 'Su', hex: '#E0F0E9' },
  { name: '荼白', pinyin: 'Tu Bai', hex: '#F3F9F1' },
  { name: '霜色', pinyin: 'Shuang Se', hex: '#E9F1F6' },
  { name: '花白', pinyin: 'Hua Bai', hex: '#C2CCD0' },
  { name: '鱼肚白', pinyin: 'Yu Du Bai', hex: '#FCEFE8' },
  { name: '莹白', pinyin: 'Ying Bai', hex: '#E3F9FD' },
  { name: '灰色', pinyin: 'Hui Se', hex: '#808080' },
  { name: '苍色', pinyin: 'Cang Se', hex: '#75878A' },
  { name: '水色', pinyin: 'Shui Se', hex: '#88ADA6' },
  { name: '乌色', pinyin: 'Wu Se', hex: '#725E82' },
  { name: '玄色', pinyin: 'Xuan Se', hex: '#622A1D' },
  { name: '缁色', pinyin: 'Zi Se', hex: '#493131' },
  { name: '煤黑', pinyin: 'Mei Hei', hex: '#312520' },
  { name: '黑色', pinyin: 'Hei Se', hex: '#000000' },
  { name: '漆黑', pinyin: 'Qi Hei', hex: '#161823' }
];

export function getRandomChineseColor() {
  return chineseColors[Math.floor(Math.random() * chineseColors.length)];
}
